name: Checkout and Create Release Version

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: mlugg/setup-zig@v2
        with:
          cache-size-limit: 0
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up environment
        run: |
          WEB_VERSION=$(curl -sSL "https://api.github.com/repos/OpenListTeam/OpenList-Frontend/releases/latest" | jq -r '.tag_name')
          echo "WEB_VERSION=${WEB_VERSION}" >> $GITHUB_ENV
          echo "GHCR_IMAGE=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          wget -qO- "https://github.com/OpenListTeam/OpenList-Frontend/releases/download/${WEB_VERSION}/openlist-frontend-dist-${WEB_VERSION}.tar.gz" | tar xz -C public/dist
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
